"""External SCH position vectors; py3gpp 0.6.0, no project source imports.

The rate matcher is a selection/permutation. Distinct integer position labels
instead of bits expose every selected input position, including repetitions.
"""
from pathlib import Path
from importlib.metadata import version
import hashlib
import importlib
import json
import numpy as np
import py3gpp as nr

assert version('py3gpp') == '0.6.0'
root = Path(__file__).parent
out = ['/* Generated by generate_rate_matching.py using py3gpp 0.6.0. */']
cases = []
for bg, z, cols in [(1, 8, 22), (2, 8, 10)]:
    n = (68 if bg == 1 else 52)*z
    start, end = cols*z-7, cols*z
    labels = np.arange(2*z, n, dtype=np.int32)
    labels[start-2*z:end-2*z] = -1
    for rv in range(4):
        for mod, qm in [('QPSK',2),('16QAM',4),('64QAM',6),('256QAM',8)]:
            for repeat in [False, True]:
                E = qm*((len(labels)//qm)*(2 if repeat else 1)//(1 if repeat else 2)+1)
                positions = nr.nrRateMatchLDPC(labels[:,None],E,rv,mod,1)
                assert len(positions)==E and np.all(positions>=2*z)
                name = f'sch_positions_{len(cases)}'
                out.append(f'static const int {name}[] = {{')
                out += ['    '+','.join(map(str,positions[i:i+24]))+',' for i in range(0,E,24)]
                out.append('};')
                cases.append(f'    {{{bg},{z},{n},{start},{end},{rv},{qm},{E},{name}}},')
out += ['static const struct { int bg,z,n,start,end,rv,qm,e; const int *positions; } sch_refs[] = {',*cases,'};']
# Unequal CB allocation, reference output labels identify each contributing CB.
labels = np.repeat(np.arange(16,544,dtype=np.int32)[:,None],3,axis=1)
for cb in range(3):
    labels[:,cb] += cb*10000
labels[169-16:176-16,:] = -1
for qm, mod in [(2,'QPSK'),(4,'16QAM'),(6,'64QAM'),(8,'256QAM')]:
    matched = nr.nrRateMatchLDPC(labels,101*qm,2,mod,1)
    lengths = [int(np.sum(matched//10000==c)) for c in range(3)]
    out.append(f'static const int sch_er_qm{qm}[3] = {{{",".join(map(str,lengths))}}};')
header = root/'sch_rate_matching_reference_vectors.h'
header.write_text('\n'.join(out)+'\n')
reference = Path(importlib.import_module('py3gpp.nrRateMatchLDPC').__file__)
manifest = dict(reference='https://github.com/catkira/py3gpp/tree/v0.6.0',
                packages={p:version(p) for p in ['py3gpp','numpy']}, cases=len(cases),
                sha256={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [header,reference,Path(__file__)]})
(root/'sch_rate_matching_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(f'Generated {len(cases)} external position vectors and four C=3 allocation cases')
