"""Generate external encoder/rate-match vectors. Requires py3gpp==0.6.0.
No project source, table or binary is read. Run from any directory.
"""
from pathlib import Path
from importlib.metadata import version
import hashlib
import json
import importlib
import numpy as np
import py3gpp as nr

assert version('py3gpp') == '0.6.0'
rng = np.random.default_rng(38212)
root = Path(__file__).parent

def literal(bits):
    s = ''.join(str(int(v)) for v in bits)
    return '\n'.join('    "'+s[i:i+96]+'"' for i in range(0,len(s),96))

polar = ['/* py3gpp 0.6.0; generated by generate_codecs.py. */',
         'static const struct { int N, K, E, iil; const char *info, *coded, *matched; } polar_refs[] = {']
for nmax, K, E, iil in [(7,40,256,1),(9,56,864,1),(9,80,512,1),(10,100,1024,0)]:
    info = rng.integers(0,2,K)
    coded = nr.nrPolarEncode(info,E,nmax=nmax,iil=bool(iil))
    matched = nr.nrRateMatchPolar(coded,K,E)
    polar += ['  {'+f'{2**nmax}, {K}, {E}, {iil},',literal(info)+',',literal(coded)+',',literal(matched)+'},']
polar.append('};\n')
(root/'polar_reference_vectors.h').write_text('\n'.join(polar))

ldpc = ['/* py3gpp 0.6.0; both encoding algorithms agree for every case. */',
        'static const struct { int bg, Zc, K; const char *info, *coded; } ldpc_refs[] = {']
for bg, sizes in [(1,[2,3,5,7,9,11,13,15]),(2,[72,80,88,104,112,120,128,144])]:
    for Z in sizes:
        fullK = (22 if bg==1 else 10)*Z
        K = fullK-7
        info = rng.integers(0,2,K)
        padded = np.full((fullK,1),-1,dtype=int)
        padded[:K,0]=info
        encoded = nr.nrLDPCEncode(padded,bg,algo='sionna')
        other = nr.nrLDPCEncode(padded,bg,algo='thangaraj')
        assert np.array_equal(encoded,other),(bg,Z)
        assert np.isin(encoded, [-1,0,1]).all()
        module = importlib.import_module('py3gpp.nrLDPCEncode')
        from py3gpp.nrDLSCHInfo import getZarray
        ils = next(i for i, sizeset in enumerate(getZarray()) if Z in sizeset)
        full_code = np.concatenate((info[:2*Z], np.maximum(encoded[:,0],0)))
        assert module._check_cw(module._load_basegraph(ils,bg),Z,full_code), (bg,Z)
        # External -1 denotes filler; the C mother-code API uses zero there.
        coded = np.maximum(encoded[:,0],0)
        ldpc += ['  {'+f'{bg}, {Z}, {K},',literal(info)+',',literal(coded)+'},']
ldpc.append('};\n')
(root/'ldpc_reference_vectors.h').write_text('\n'.join(ldpc))
print('Generated 4 Polar and 16 LDPC vectors; py3gpp',version('py3gpp'),'numpy',np.__version__)

manifest = {"packages": {p: version(p) for p in ("py3gpp", "numpy", "scipy")},
            "seed": 38212,
            "source": "https://github.com/catkira/py3gpp/tree/v0.6.0",
            "sha256": {}}
package_root = Path(nr.__file__).parent
for path in sorted(package_root.rglob('*')):
    if path.is_file() and path.suffix in ('.py', '.csv'):
        manifest['sha256'][str(path.relative_to(package_root))] = hashlib.sha256(path.read_bytes()).hexdigest()
for name in ('polar_reference_vectors.h','ldpc_reference_vectors.h'):
    manifest['sha256'][name] = hashlib.sha256((root/name).read_bytes()).hexdigest()
(root/'codec_reference_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
