"""Regenerate fixed vectors using NumPy SVD, not this project's Gram inverse.
Run: python3 PHY/tests/reference_vectors/generate_mumimo.py
"""
from pathlib import Path
import numpy as np

base = np.array([[2+1j, .5-.2j, -.3+.4j, .2+.1j],
                 [.1-.5j, 1.5+.3j, .4+.2j, -.2+.6j],
                 [.3+.1j, -.4+.2j, 1.8-.7j, .5+.4j],
                 [-.2+.3j, .6-.1j, .2+.5j, 1.3+.8j]])
channels = [base, base[[2, 0, 3, 1], :] * np.array([1j, -.5j, 2, -.75])[:, None],
            np.array([[1, 0, 0, 0], [1, .1, 0, 0], [0, 0, 1, 0], [0, 0, 1, .2]]) @ base]
text = ['/* Generated by generate_mumimo.py; NumPy '+np.__version__+' SVD pinv. */',
        '#ifndef MUMIMO_REFERENCE_VECTORS_H', '#define MUMIMO_REFERENCE_VECTORS_H',
        '#define MUMIMO_REFERENCE_CASES 3']
for name, matrices in [('mumimo_reference_h', channels),
                       ('mumimo_reference_w', [np.linalg.pinv(h) / np.linalg.norm(np.linalg.pinv(h), axis=0) / 2 for h in channels])]:
    text.append('static const cx_t '+name+'[3][4][4] = {')
    for matrix in matrices:
        text.append('  {')
        for row in matrix:
            text.append('    {'+', '.join(f'CX_MAKE({z.real:.17g}, {z.imag:.17g})' for z in row)+'},')
        text.append('  },')
    text.append('};')
text.append('#endif\n')
Path(__file__).with_name('mumimo_reference_vectors.h').write_text('\n'.join(text))
print('Generated 3 complex 4x4 SVD reference cases; condition numbers:',
      [float(np.linalg.cond(h)) for h in channels])
